[project]
name = "tester"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = ["colorama>=0.4.6"]

[dependency-groups]
dev = ["coverage>=7.8.2", "ruff>=0.11.11", "tox>=4.26.0"]
