name: Push changes to repos

on:
  push:
    branches: [ "master" ]
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:
    uses: ./.github/workflows/build.yaml

  push:
    name: push
    needs: [build]
    runs-on: ubuntu-latest

    steps:
      - name: Download build files
        uses:  actions/download-artifact@v3
        with:
          name: build
          path: examiner

      - name: Download commit message
        uses:  actions/download-artifact@v3
        with:
          name: commit_msg
          path: ~/commit

      - name: Set commit msg as env
        run: |
          cat ~/commit/commit.env >> "$GITHUB_ENV"

      - name: Deploy to external repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          # @see https://cpina.github.io/push-to-another-repository-docs/setup-using-ssh-deploy-keys.html#setup-ssh-deploy-keys
          SSH_DEPLOY_KEY: ${{ secrets.PYTHON_EXAMINATION_ACTIONS_SSH }}
        with:
          source-directory: examiner
          destination-github-username: dbwebb-se
          destination-repository-name: python
          user-name: python-examination-actions
          target-directory: .dbwebb/test/examiner
          target-branch: "master"
          commit-message: $GIT_COMMIT_DESC